In [1]:
import numpy as np

a = np.array([10,20,30,40])
print(np.append(a,90))

b = np.array([[10,20], [30,40]])
print(np.append(b,[66,89]))

[10 20 30 40 90]
[10 20 30 40 66 89]


In [2]:
print(np.insert(a,1,25))   #Array,index,value

[10 25 20 30 40]


In [3]:
print(np.insert(b,1,[50,60], axis = 0))

[[10 20]
 [50 60]
 [30 40]]


In [4]:
print(np.delete(a,1))

[10 30 40]
