In [7]:
import numpy as np

a = np.array([10,20,30,40])
print(np.sum(a))
print(np.min(a))
print(np.max(a))
print(np.size(a))
print(np.mean(a))
print(np.cumsum(a))
print(np.cumprod(a))

100
10
40
4
25.0
[ 10  30  60 100]
[    10    200   6000 240000]


In [12]:
import numpy as np
a = [100,234,160,199,200,250,130]
b = [10,20,30,50,40,30,10]

price = np.array(a)
quantity = np.array(b)
print(price, "\n", quantity)

c = (np.cumprod([price, quantity], axis = 0))
print(c[1].sum())


[100 234 160 199 200 250 130] 
 [10 20 30 50 40 30 10]
37230
