In [1]:
a = [50,60,70]
b = [34,67,65]
print(a+b)

[50, 60, 70, 34, 67, 65]


In [2]:
#Concatenate
import numpy as np
arr1 = np.array([[30,40], [45, 50]])
arr2 = np.array([[2,4], [6,5]])
print(np.concatenate([arr1,arr2]))

[[30 40]
 [45 50]
 [ 2  4]
 [ 6  5]]


In [3]:
print(np.concatenate([arr1,arr2], axis =0))

[[30 40]
 [45 50]
 [ 2  4]
 [ 6  5]]


In [4]:
print(np.concatenate([arr1,arr2], axis =1))

[[30 40  2  4]
 [45 50  6  5]]


In [5]:
print(np.hstack([arr1,arr2]))    #Horizontal Concatenation

[[30 40  2  4]
 [45 50  6  5]]


In [6]:
print(np.vstack([arr1,arr2]))   #Vertical Concatenation

[[30 40]
 [45 50]
 [ 2  4]
 [ 6  5]]


In [7]:
a = np.array([10,20,30,40,50,60])
print(np.array_split(a,3))   # To split an array

[array([10, 20]), array([30, 40]), array([50, 60])]
