In [1]:
import numpy as np
arr = np.array([13,41,2,4,78,23])
print(np.sort(arr))

[ 2  4 13 23 41 78]


In [2]:
s = np.where(arr == 4)
print(s)

S = np.where(arr % 2 == 0)
print(S)

(array([3]),)
(array([2, 3, 4]),)


In [3]:
import numpy as np
ar = np.array([2,3,4,5,6])
ss = np.searchsorted(ar, 4)  #Only use on arrays which are already sorted
print(ss)

2


In [5]:
#Filter
import numpy as np
arr = np.array([20,30,40,50])
fa = [True, False, True, False]
new = arr[fa]
print(new)


[20 40]


In [11]:
fa = arr > 35
new = arr[fa]
print(new)

[40 50]
